menu:
  title: NCIT Alumns
  main:
    - title: Home
      link: /
    - title: Alumni Directory
      subMenu:
        - category: Graduation Yearss
          inRange: true
          rangeStart: 2000
          rangeEnd: 2024 #default to current year
          link: /profiles/{range}
        - category: Departments
          items:
            - SE
            - IT
            - ELX
            - COM
            - CIVIL
            - BCA
            - BBA
          link: /profiles/{item} 
    - title: Events
      link: /events
    - title: Blog
      link: /blog
    - title: About
      link: /about
    - title: Contact Us
      link: /contact

footer:
  tagline: Open Alumn Portal - An alumni portal connecting NCIT Alumns maintained by NOSK and contributors.
  items:
  - title: About
    link: #
  - title: GitHub
    link: https://github.com/noskofficial/ncitalums
  - title: Contribute Now
    link: https://github.com/noskofficial/ncitalums/blob/develop/CONTRIBUTING.md

featured:
  profiles: 
  -  "2005/nitesh-rijal"
  -  "2016/mukhez"
  -  "2021/satyarajawasth1" # slug
  blogs:
  -  "2017/ncit-alumni-reflections"

events:
  upcoming:
    title: Upcoming Events
    link: "https://raw.githubusercontent.com/noskofficial/noskofficial.github.io/main/events.json"